---
- name: Add or update user password
  hosts: all

  tasks:
  - name: Change 'fatih' password
    user:
      name: fatih
      update_password: always
      password: "{{ newpassword | password_hash('sha512') }}"
