---
- name: Copy file from local to remote clients
  hosts: all

  tasks:
  - name: Copying file
    become: true
    copy:
     src: /home/sevcanozdemir/some.cfg
     dest: /tmp
     owner: sevcanozdemir
     group: sevcanozdemir
     mode: 0644
