---
- name: Install NCPA Agent
  hosts: all
  become_method: su
  gather_facts: yes
  vars:
   rpm7_path: "/ansible/agents-repo/ncpa/ncpa-2.4.0.el7.x86_64.rpm"
   rpm8_path: "/ansible/agents-repo/ncpa/ncpa-2.4.0.el8.x86_64.rpm"
   rpm7_name: "ncpa-2.4.0.el7.x86_64.rpm"
   rpm8_name: "ncpa-2.4.0.el8.x86_64.rpm"
   destinationpath: "/root/agents/ncpa"
  tasks:
  - name: Install NCPA
    block:
      - name: Create directories
        file:
          path: "{{ destinationpath }}"
          state: directory
          mode: '0755'

      - name: Copy File v7
        copy:
          src: "{{ rpm7_path }}"
          dest: "{{ destinationpath }}"
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "7")


      - name: Copy File v8
        copy:
          src: "{{ rpm8_path }}"
          dest: "{{ destinationpath }}"
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "8")

      - name: Find File v7
        shell:  " find {{ destinationpath }} -iname {{ rpm7_name }} "
        register: redhat7_path
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "7")


      - name: Find File v8
        shell:  " find {{ destinationpath }} -iname {{ rpm8_name }} "
        register: redhat8_path
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "8")


      - name: Install package 7
        shell: " rpm -ivh {{ redhat7_path.stdout }} "
        register: ncpa_result
        failed_when: ncpa_result.rc != 0
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "7")


      - name: Install package 8
        shell: "rpm -ivh {{ redhat8_path.stdout }} "
        register: ncpa_result
        failed_when: ncpa_result.rc != 0
        when: (ansible_facts['os_family']=="RedHat" and ansible_facts['distribution_major_version'] == "8")


    rescue:
        - debug:
             msg: 'NCPA kurulumunda hata var. Loglarini kontrol ediniz !!!'

