- hosts: all
  become: yes
  become_method: su
  gather_facts: no
  vars:
    myuser: "root"
    mypassword: "Passw@rd123"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
